rates <- c(33, 22, 9, 9, 5, 2)
# barplot(rates)
names(rates) <- c("문재인", "안희정", "황교안", "안철수", "이재명", "유승민")
b1 <- barplot(rates, axes = FALSE, col = c("skyblue", "skyblue", "white", "green", "skyblue", "lightblue"), cex.names = 1.5)
text(x = b1, y = rates + c(rep(-3, 4), rep(1.5, 2)), labels = rates, cex = 1.5)
title(main = "차기 대선주자 지지율(%)", cex.main = 2)